@startuml
title architecture diagram

skinparam linetype ortho

rectangle "User" as User

rectangle "frontend" as Browser {
  component "index.html" as index
  component "script.js" as script
  component "style.css" as style
}

rectangle "backend" as backend {
  component "insert.php" as insert
  component "start_game.php" as start
  component "get.php" as get
  component "delete.php" as delete
  component "db_connect.php" as dbconn
  database "MySQL Database" as DB
}

rectangle "embedded" as embedded{
    component "ssd1306" as oled 
    component "joystick" as joystick
    component "button" as bttn 
    component "buzzer" as bzzr
    component "ESP32" as ESP32
}

User --> embedded
User --> index
dbconn --> DB : db_connect.php
ESP32 --> backend : API
script --> ESP32 : debug
delete --> dbconn
get --> dbconn
insert --> dbconn
start --> dbconn
ESP32 --> oled : I2C
joystick --> ESP32
ESP32 --> bzzr
bttn --> ESP32
style --> index
script --> index
script --> backend


@enduml

